### ISSUE TITLE
Add support for function and parameters event also custom vars

### ISSUE THREAD

**Issue by dunak-debug** [Mojito-Fivem/bt-target#11]
It would be good to extend parameter event also to function where you would pass just variable containing function.

`event = onPressed

onPressed = function(entityHit, customVars??)`

Also it would be good to have maybe addPlayerModel that will send you player Id to event/function that way you know for who player you pressed that

**Comment by LiamDormon** [comment]
Create a pull request if you want to see this but I have no intention of doing this.
