### ISSUE TITLE
paramters on targeting script

### ISSUE THREAD

**Issue by TheTechJess** [Mojito-Fivem/bt-target#17]
Hello, I was curious to know if it's possible to get bt target to work with specific models and bones, but not throughout the whole game, just the one entity

like  for example

> 	local bones = {
>         "boot"
>     }
> 
> 	exports["bt-target"]:AddTargetBone(bones, {
> 		options = {
> 			{
> 			event = "emtytrash",
> 			icon = "fas fa-door-open",
> 			label = "Toss in Trash",
> 			job = {"garbage"},
> 			eventParams = {PlayerVehicle = worktruckplate}
> 			},
> 
> 		},
> 		distance = 1.5
> 		})

With this I tried to get it to check if its the work vehicle, and if it isn't, to not display

**Comment by LiamDormon** [comment]
No this does not work with my version, you can't just add an extra "eventParams" field and get it to magically work

**Comment by TheTechJess** [comment]
All good! wanted to check :)
