### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by haitham1337** [Mojito-Fivem/bt-target#2]
Citizen.CreateThread(function()
AddTargetBone(bones, {
options = {
{
event = "door",
icon = "fas fa-door-open",
label = "Toggle Door",
},
{
event = "unlock",
icon = "fas fa-door-open",
label = "Unlock Door",
},
},
job = {"police", "ambulance", "mechanic"},
distance = 1.5
})
end)

bad argument #1 to 'pairs' table expected, got nill

function AddTargetBone(bones, parameteres)
for _, bone in pairs(bones) do
Bones[bone] = parameteres
end
end

**Comment by haitham1337** [comment]
this is my issues

**Comment by piliatchoo** [comment]
and im add this in my script

function AddEntityZone(name, entity, options, targetoptions)
Zones[name] = EntityZone:Create(entity, options)
Zones[name].targetoptions = targetoptions
end


exports("AddEntityZone", AddEntityZone)

**Comment by LiamDormon** [comment]
You need to pass a table of bones, not a nil variable, read the documentation
