### ISSUE TITLE
Target stops working if 2 zones are too close

### ISSUE THREAD

**Issue by bradyy** [Mojito-Fivem/bt-target#23]
I have an event on a vehicle bone and target on an NPC. If I park my vehicle near the NPC and try to target the NPC, it shows events of the vehicle instead, after selecting anything on it or even pressing ESC to hide the events, the target eye stops working until I restart the resource.

Using version 1.6.3.

**Comment by LiamDormon** [comment]
Don't overlap zones. Try out OfficialNoms' fork, I believe he's taken a different approach to vehicle bones that may solve this problem. His version however doesn't have the same security fixes that I've added to mine but if his bone implementation works better than TheeDeer's I may merge it into this fork.

**Comment by bradyy** [comment]
> Don't overlap zones. Try out OfficialNoms' fork, I believe he's taken a different approach to vehicle bones that may solve this problem. His version however doesn't have the same security fixes that I've added to mine but if his bone implementation works better than TheeDeer's I may merge it into this fork.

Haven't had the time to check out his fork, but for now not overlapping zones is a better idea. Thank you.
