### ISSUE TITLE
Menu stuck with large CircleZone

### ISSUE THREAD

**Issue by FokkenClown** [Mojito-Fivem/bt-target#26]
Hey guys

Currently I am using a circle zone, i press alt and it opens without issue.
But i cannot close it myself while in the zone.

I added a script for heli rental and wanted to hook it up to a heli pad

```
Citizen.CreateThread(function()
	exports['bt-target']:AddCircleZone("HeliRental", vector3(-725.25, -1443.81, 5.0), 8.0, {
		name="HeliRental",
		heading=91,
		debugPoly=false,
		minZ=30.79,
		maxZ=30.99
		}, {
			options = {
				{
					event = "Helirental:openRentMenu",
					icon = "fas fa-helicopter",
					label = "Rent helicopter",
					job = {'all'},
				},
				{
					event = "Helirental:openRentMenu",
					icon = "fas fa-helicopter",
					label = "Buy helicopter",
					job = {'all'},
					shouldShow = function()
						-- if condition then
						-- 	return true -- Optional function, return true to show, false to hide option. 
						-- end
						return false
					end
				}
			},
			distance = 8.0
		})
end)
```

**Comment by LiamDormon** [comment]
Fix Formatting

**Comment by FokkenClown** [comment]
> Fix Formatting

fixed, sorry for bad format

**Comment by LiamDormon** [comment]
Do you get errors? Have you tried not using an enormous zone?

**Comment by FokkenClown** [comment]
no errors, and the zone is the size of the helipad.

The problem is that when you look at the helipad where its setup you cannot press alt again to close it, but if you look out of the zone you can press alt to close it

**Comment by FokkenClown** [comment]
Alternativly, is there a way to use AddTargetModel with AddCircleZone.
So say I have a ped spawned in, but only trigger bt-target if in the zone

**Comment by LiamDormon** [comment]
No, no such function exists. I don't have time to set up a repro for this. You can try making the zone not so huge, I've never had a problem with circlezones before, or a problem reported to me.
