### ISSUE TITLE
multiple vehicles bone and multiple models

### ISSUE THREAD

**Issue by alessiocavallo** [Mojito-Fivem/bt-target#4]
i've added 3 different TargetsBones, one for police job, one for mechanic job and one for ambulance job, in the 3 different resources. If i join to the server only one of the 3 works, if i re-ensure all the resources all starts working.
the question is, is it possible to add multiple bones? 
Same story for player models, i've used `mp_m_freemode_01` and `mp_f_freemode_01` to create 3 different menus, only 1 of the three works.
Am i missing something? or i need to create a "shared" menu.

**Comment by LiamDormon** [comment]
Could you provide a code sample @Alessio-WAY Not entirely sure what you mean

**Comment by alessiocavallo** [comment]
```
Citizen.CreateThread(function()
    local objects= {
	`mp_m_freemode_01`,
	`mp_f_freemode_01`
    }
    AddTargetModel(objects, {
        options = {
            {
                event = "menu1",
                icon = "fas fa-dumpster",
                label = "action1",
            },
        },
        job = {"ambulance"}
        distance = 2.5
    })
    AddTargetModel(objects, {
        options = {
            {
                event = "menu2",
                icon = "fas fa-dumpster",
                label = "action2",
            },
        },
        job = {"police"}
        distance = 2.5
    })
end)
```


You can't do this.
But i've made an external script to handle such type of menus.

When it's done and tested ill'add the code

**Comment by LiamDormon** [comment]
It looks like the issue stems from the setter adding to the table with `Models[model] = ...` which will overwrite any other entry for that model and therefore it will only pickup the last entry. I'll see if using table.insert instead fixes it alternatively I could add an individual jobs param to each option.

**Comment by LiamDormon** [comment]
I've pushed an update so you should be able to use it like this:
```js
    const objects = [
        GetHashKey("prop_cs_dumpster_01a"),
        GetHashKey("p_dumpster_t"),
        GetHashKey("prop_dumpster_01a"),
        GetHashKey("prop_dumpster_02a"),
        GetHashKey("prop_dumpster_02b"),
        GetHashKey("prop_dumpster_4a"),
        GetHashKey("prop_dumpster_3a"),
        GetHashKey("prop_dumpster_3b")
    ]
    exports["bt-target"].AddTargetModel(objects, {
        "options": [
            {
                "event": "menu1",      
                "job": ["police"],
                "icon": "fas fa-dumpster",
                "label": "action1"
            },
            {
                "event": "menu2",
                "job": ["ambulance"],
                "icon": "fas fa-dumpster",
                "label": "action2"
            }
        ],
        "distance": 2.5
    })
```

**Comment by alessiocavallo** [comment]
thanks man good job i appreciate it.
